name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Run code quality checks
        run: pnpm run check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Run tests
        run: pnpm run test:run

      - name: Run build check
        run: pnpm run build
